dbt_ecommerce:
  outputs:
    dev:
      type: postgres
      host: big_data_postgres
      user: admin
      pass: admin
      port: 5432
      dbname: big_data_postgres
      schema: public
      threads: 4
  target: dev
  #
